<div class="order-details">
    <!-- Other order details -->
    <div class="sales-order-additional">
        <div class="field">
            <h1>hfhg</h1>
            <label class="label" for="apply_refund_fee">Apply Refund Fee</label>
            <div class="control">
                <input type="checkbox" name="apply_refund_fee" id="apply_refund_fee" value="1" class="checkbox" />
                <input type="checkbox" name="apply_refund_fee" id="apply_refund_fee" value="1" class="checkbox" />

            </div>
        </div>
    </div>
</div>
